name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout service 1
      uses: actions/checkout@v4
      with:
        ref: init_test_app
        repository: mi8-wc3/strikes-and-gutters
        submodules: true
        path: backend

    - name: Checkout service 2
      uses: actions/checkout@v4
      with:
        repository: mi8-wc3/frontend-service
        ref: init_auth_page
        path: frontend

    - name: Deploy service 1 to CapRover
      uses: caprover/action-deploy@v1.0.1
      with:
        server: '${{ secrets.CAPROVER_SERVER }}'
        app: '${{ secrets.APP_NAME }}'
        token: '${{ secrets.APP_TOKEN }}'
