name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout service 1
        uses: actions/checkout@v4
        with:
          ref: init_test_app
          repository: mi8-wc3/strikes-and-gutters
          submodules: true
          path: backend

      - name: Checkout service 2
        uses: actions/checkout@v4
        with:
          repository: mi8-wc3/frontend-service
          ref: init_auth_page
          path: frontend

        # Создаем архив с backend и деплоим его
      - name: Create deploy archive for backend
        run: |
          cd backend
          tar -cvf ../deploy-backend.tar .

      - name: Deploy backend service
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.BACKEND_APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          tarball: 'deploy-backend.tar'

        # Создаем архив с frontend и деплоим его
      - name: Create deploy archive for frontend
        run: |
          cd frontend
          tar -cvf ../deploy-frontend.tar .

      - name: Deploy frontend service
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.FRONTEND_APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          tarball: 'deploy-frontend.tar'
